type DailyContent = {
  verse: { text: string; source: string };
  hadith: { text: string; source: string };
  fiqh: string;
  history: string;
  quote: { text: string; source: string };
};

const VERSES = [
  { text: 'Ey iman edenler! Sabır ve namazla yardım dileyin...', source: 'Bakara, 153' },
  { text: 'Kalpler ancak Allah\'ı anmakla huzur bulur.', source: 'Ra\'d, 28' },
  { text: 'Namazı dosdoğru kılın, zekâtı verin ve rükû edenlerle birlikte rükû edin.', source: 'Bakara, 43' },
  { text: 'Muhakkak ki namaz, hayâsızlıktan ve kötülükten alıkoyar.', source: 'Ankebût, 45' },
  { text: 'Allah\'a karşı gelmekten sakının ki kurtuluşa eresiniz.', source: 'Âl-i İmrân, 200' },
  { text: 'Şüphesiz güçlükle beraber bir kolaylık vardır.', source: 'İnşirâh, 5-6' },
  { text: 'Kim Allah\'a tevekkül ederse, O ona yeter.', source: 'Talâk, 3' },
  { text: 'Rabbinize yalvararak ve gizlice dua edin.', source: 'A\'râf, 55' },
  { text: 'Allah sabredenleri sever.', source: 'Âl-i İmrân, 146' },
  { text: 'Bana dua edin, size karşılık vereyim.', source: 'Mü\'min, 60' },
  { text: 'De ki: Rabbim! İlmimi artır.', source: 'Tâhâ, 114' },
  { text: 'İyilikle kötülük bir olmaz. Kötülüğü en güzel şekilde önle.', source: 'Fussilet, 34' },
  { text: 'Kim zerre kadar hayır yapmışsa onu görür.', source: 'Zilzâl, 7' },
  { text: 'Allah, her güçlük ile birlikte bir kolaylık yaratmıştır.', source: 'İnşirâh, 5' },
  { text: 'Rabbim! Beni ve soyumdan gelecekleri namazı dosdoğru kılanlardan eyle.', source: 'İbrâhîm, 40' },
  { text: 'Namazlara ve orta namaza devam edin.', source: 'Bakara, 238' },
  { text: 'Şüphesiz namaz, müminlere belirli vakitlerde farz kılınmıştır.', source: 'Nisâ, 103' },
  { text: 'Her nefis ölümü tadacaktır.', source: 'Âl-i İmrân, 185' },
  { text: 'Allah\'ın rahmetinden ümidinizi kesmeyin.', source: 'Zümer, 53' },
  { text: 'Rabbinizden bağışlanma dileyin. Çünkü O, çok bağışlayıcıdır.', source: 'Nûh, 10' },
  { text: 'Size verilen her şey dünya hayatının geçici metaıdır.', source: 'Kasas, 60' },
  { text: 'Onlar ayakta, oturarak ve yanları üzerine yatarak Allah\'ı anarlar.', source: 'Âl-i İmrân, 191' },
  { text: 'Biz insanı en güzel biçimde yarattık.', source: 'Tîn, 4' },
  { text: 'Rabbim! Göğsümü aç, işimi kolaylaştır.', source: 'Tâhâ, 25-26' },
  { text: 'Allah kuluna kâfi değil mi?', source: 'Zümer, 36' },
  { text: 'Hiçbir günahkâr başkasının günahını yüklenmez.', source: 'En\'âm, 164' },
  { text: 'Ey iman edenler! Allah\'ı çokça zikredin.', source: 'Ahzâb, 41' },
  { text: 'Şüphesiz ben tövbe edenleri, iman edenleri ve salih amel işleyenleri bağışlarım.', source: 'Tâhâ, 82' },
  { text: 'İnsan için ancak çalıştığının karşılığı vardır.', source: 'Necm, 39' },
  { text: 'Allah, bir kimseyi ancak gücünün yettiği şeyle yükümlü kılar.', source: 'Bakara, 286' },
  { text: 'Kim bir iyilik getirirse ona on katı vardır.', source: 'En\'âm, 160' },
];

const HADITHS = [
  { text: 'İnsanlara teşekkür etmeyen, Allah\'a da şükretmez.', source: 'Tirmizî' },
  { text: 'Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.', source: 'Buhârî' },
  { text: 'Amellerin en hayırlısı vaktinde kılınan namazdır.', source: 'Buhârî' },
  { text: 'Cennetin anahtarı namazdır.', source: 'Tirmizî' },
  { text: 'Temizlik imanın yarısıdır.', source: 'Müslim' },
  { text: 'Güzel söz sadakadır.', source: 'Buhârî' },
  { text: 'Mümin, mümine aynadır.', source: 'Ebû Dâvûd' },
  { text: 'Allah yumuşak davranmayı sever ve yumuşaklığa verdiğini sertliğe vermez.', source: 'Müslim' },
  { text: 'İki nimet vardır ki insanların çoğu bunlarda aldanmıştır: Sağlık ve boş vakit.', source: 'Buhârî' },
  { text: 'Sizin en hayırlınız ahlâkı en güzel olanınızdır.', source: 'Buhârî' },
  { text: 'Kim Allah\'a ve ahiret gününe inanıyorsa, komşusuna iyilik etsin.', source: 'Buhârî' },
  { text: 'Duanın ibadetin özü olduğunu biliniz.', source: 'Tirmizî' },
  { text: 'Bir Müslümanın diğer Müslüman üzerinde beş hakkı vardır.', source: 'Buhârî' },
  { text: 'Kıyamet gününde kulun ilk hesaba çekileceği şey namazdır.', source: 'Ebû Dâvûd' },
  { text: 'Kim bana bir karış yaklaşırsa, ben ona bir arşın yaklaşırım.', source: 'Buhârî' },
  { text: 'Sabır acı bitkidir ama meyvesi tatlıdır.', source: 'Beyhakî' },
  { text: 'Dünya ahiretin tarlasıdır.', source: 'Deylemî' },
  { text: 'İlim Çin\'de bile olsa arayınız.', source: 'Beyhakî' },
  { text: 'Beş vakit namaz, büyük günahlardan kaçınıldıkça aralarındaki günahlara kefârettir.', source: 'Müslim' },
  { text: 'Hiçbiriniz kendisi için istediğini kardeşi için de istemedikçe iman etmiş olmaz.', source: 'Buhârî' },
  { text: 'Her kim bir hayra yol gösterirse, o hayrı yapanın sevabı kadar sevap alır.', source: 'Müslim' },
  { text: 'Allah\'ım! Senden hidayet, takva, iffet ve gönül zenginliği istiyorum.', source: 'Müslim' },
  { text: 'Müminin niyeti amelinden hayırlıdır.', source: 'Taberânî' },
  { text: 'Güleryüzle karşılaşmayı küçümseme.', source: 'Müslim' },
  { text: 'Namaz müminin miracıdır.', source: 'Suyûtî' },
  { text: 'En üstün cihat, nefse karşı yapılan cihattır.', source: 'Tirmizî' },
  { text: 'Allah Teâlâ sizin dış görünüşünüze değil, kalplerinize bakar.', source: 'Müslim' },
  { text: 'Tövbe eden günahından dönen gibidir.', source: 'İbn Mâce' },
  { text: 'Kim bir ağaç dikerse, ondan yenen her meyve ona sadakadır.', source: 'Müslim' },
  { text: 'Cehennem, şehvetlerle; cennet ise nefsin hoşlanmadığı şeylerle kuşatılmıştır.', source: 'Buhârî' },
  { text: 'Her kim farz namazları bilerek terk ederse Allah\'ın koruması ondan kalkar.', source: 'Ahmed b. Hanbel' },
];

const FIQH = [
  'Abdestin sünnetleri nelerdir? Misvak kullanmak, elleri bileklere kadar üç kez yıkamak, ağza ve burna su çekmek.',
  'Namazda ta\'dîl-i erkân nedir? Rükû ve secdelerde en az bir tesbih söyleyecek kadar beklemektir.',
  'Vitir namazı kaç rekâttır? Hanefi mezhebine göre 3 rekâttır ve vaciptir.',
  'Seferi (yolcu) namazı nedir? 90 km ve üzeri yolculukta 4 rekâtlık farzlar 2 rekât olarak kılınır.',
  'Kazâ namazı nedir? Vaktinde kılınamayan farz namazların sonradan kılınmasıdır.',
  'Mest üzerine mesh ne kadar sürer? Mukim için 24 saat, yolcu için 72 saattir.',
  'Namazı bozan durumlar nelerdir? Konuşmak, gülmek, yemek-içmek, kıbleye arkasını dönmek.',
  'Teheccüd namazı ne zaman kılınır? Yatsı namazından sonra, imsak vaktine kadar kılınan nafile namazdır.',
  'Secdede okunacak tesbih hangisidir? "Sübhâne rabbiye\'l-a\'lâ" en az üç kez okunur.',
  'Namazda kıraatin hükmü nedir? Fâtiha ve zamm-ı sûre okumak (ilk iki rekâtta) farzdır.',
  'Cuma namazı kimlere farzdır? Akıl bâliğ, hür, erkek, mukim, sağlıklı Müslümanlara.',
  'Namazda kahkaha abdesti bozar mı? Evet, hem namazı hem abdesti bozar.',
  'İftitah tekbiri nedir? Namaza "Allahu Ekber" diyerek başlamaktır; farz-ı ayndır.',
  'Müekked sünnet nedir? Hz. Peygamber\'in devamlı kıldığı, nadiren terkettiği sünnet namazlardır.',
  'Gusül gerektiren haller nelerdir? Cünüplük, hayız ve nifas hallerinin sona ermesi.',
  'Teyemmüm nasıl yapılır? Temiz toprağa iki kez vurarak yüzü ve kolları mesh etmektir.',
  'Secde-i sehiv ne zaman yapılır? Namazda vacip bir işlem unutulduğunda veya yanlış yapıldığında.',
  'Abdesti bozan durumlar nelerdir? Alt taraftan çıkan her şey, kan akması, uyumak, bayılmak.',
  'İstihare namazı nedir? Bir konuda Allah\'tan hayırlısını istemek için kılınan 2 rekât namazdır.',
  'Kunut duaları ne zaman okunur? Vitir namazının 3. rekâtında rükûdan önce okunur (Hanefi).',
  'Kadınların namazda örtünmesi gereken yerler neresidir? Yüz, eller ve ayaklar hariç tüm beden.',
  'Sabah namazının sünneti kaç rekâttır? 2 rekât olup en kuvvetli sünnetlerdendir.',
  'Teravih namazı kaç rekâttır? 20 rekât olup Ramazan\'da kılınır.',
  'Bayram namazı nasıl kılınır? 2 rekât olup her rekâtta 3 fazla tekbir alınır.',
  'Cenaze namazında kaç tekbir alınır? 4 tekbir alınır, rükû ve secde yoktur.',
  'Namazda niyet nasıl edilir? Kalben hangi namazı kılacağını bilmek yeterlidir.',
  'Sübhaneke duası ne zaman okunur? Namaza başlarken iftitah tekbirinden sonra okunur.',
  'Ettehiyyatü ne zaman okunur? Her oturuşta, tahiyyatta okunur.',
  'Salli-Bârik duaları ne zaman okunur? Son oturuşta Ettehiyyatü\'den sonra okunur.',
  'Namazda uyuyakalma durumunda ne yapılır? Uykudan uyanınca kazâ namazı olarak kılınır.',
  'Mushafa abdestsiz dokunulur mu? Hayır, Kur\'an-ı Kerim\'e abdestsiz dokunulmaz.',
];

const HISTORY = [
  'İstanbul\'un fethi yıldönümü (29 Mayıs 1453).',
  'Hz. Muhammed\'in (s.a.v.) Medine\'ye hicreti (622).',
  'Çanakkale Zaferi (18 Mart 1915).',
  'Kur\'an-ı Kerim\'in ilk ayetleri Hira mağarasında nazil oldu.',
  'Mescid-i Nebevi\'nin inşası (622).',
  'Bedir Savaşı - İslam tarihinin ilk büyük zaferi (624).',
  'Mescid-i Aksa\'nın kıble olarak belirlenmesi.',
  'Hudeybiye Antlaşması (628).',
  'Mekke\'nin fethi (630).',
  'Veda Hutbesi - Hz. Peygamber\'in son hutbesi (632).',
  'Endülüs İslam medeniyetinin kuruluşu (711).',
  'Selçuklu Devleti\'nin kuruluşu (1037).',
  'Malazgirt Zaferi ve Anadolu\'nun kapılarının açılması (1071).',
  'Osmanlı Devleti\'nin kuruluşu (1299).',
  'Fatih Sultan Mehmet\'in tahta çıkışı (1451).',
  'Süleymaniye Camii\'nin açılışı (1557).',
  'Kudüs\'ün Selahaddin Eyyubi tarafından fethi (1187).',
  'İmam Buhari\'nin Sahih-i Buhari eserini tamamlaması.',
  'İlk Osmanlı medresesi İznik\'te açıldı (1330).',
  'Topkapı Sarayı\'nın inşaatının tamamlanması (1478).',
  'Kıbrıs\'ın fethi (1571).',
  'Kanuni Sultan Süleyman\'ın tahta çıkışı (1520).',
  'Mimar Sinan\'ın Selimiye Camii\'ni tamamlaması (1575).',
  'Hz. Ömer döneminde Kudüs\'ün fethi (638).',
  'İlk Türkçe Kur\'an meal çalışmaları.',
  'Sakarya Meydan Muharebesi (1921).',
  'Büyük Taarruz ve Başkomutanlık Meydan Muharebesi (1922).',
  'Diyanet İşleri Başkanlığı\'nın kuruluşu (1924).',
  'İslam\'da ilk ezan Hz. Bilal tarafından okundu.',
  'Hz. Ebubekir\'in halifeliği ve Kur\'an\'ın mushaf haline getirilmesi.',
  'Türkiye\'nin NATO\'ya girişi (1952).',
];

export function getDailyContent(date: Date): DailyContent {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000,
  );
  return {
    verse: VERSES[dayOfYear % VERSES.length],
    hadith: HADITHS[dayOfYear % HADITHS.length],
    fiqh: FIQH[dayOfYear % FIQH.length],
    history: HISTORY[dayOfYear % HISTORY.length],
    quote: VERSES[(dayOfYear + 7) % VERSES.length],
  };
}
